name: icon_font_generator
version: 4.0.0
description: >-
  Converts SVG icons to OTF font and generates Flutter-compatible class.
  Provides an API and a CLI tool.
homepage: https://github.com/ScerIO/icon_font_generator

environment:
  sdk: '>=3.9.2 <4.0.0'

dependencies:
  args: ^2.4.0
  collection: ^1.19.1
  dart_style: ^3.1.2
  fixnum: ^1.1.1
  logger: ^2.6.1
  meta: ^1.17.0
  path: ^1.9.1
  path_parsing: ^1.1.0
  recase: ^4.1.0
  typed_data: ^1.4.0
  vector_math: ^2.2.0
  web: ^1.1.1
  xml: ^6.6.1
  yaml: ^3.1.3
  

dev_dependencies:
  lints: ^6.0.0
  test: ^1.23.1
  
executables:
  generator: generator